---
- name: Install docker
  gather_facts: No
  hosts: all 
  become: yes 
  become_method: sudo 

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
